# Makefile for Watcom C

BIN0=hello.exe
SRC0=hello.c

BIN1=winhello.exe
SRC1=winhello.c

BIN2=msgbox.exe
SRC2=msgbox.c

CC=wcl386
COPT=-zq -ox -bt=nt
LCON=-l=nt
LGUI=-l=nt_win

!ifdef __UNIX__
RM=rm -f
!else
RM=del
!endif

all: $(BIN0) $(BIN1) $(BIN2)

$(BIN0): $(SRC0)
	$(CC) $(COPT) $(SRC0) $(LCON)

$(BIN1): $(SRC1)
	$(CC) $(COPT) $(SRC1) $(LGUI)

$(BIN2): $(SRC2)
	$(CC) $(COPT) $(SRC2) $(LGUI)

clean:
	$(RM) $(BIN0)
	$(RM) $(BIN1)
	$(RM) $(BIN2)
